n3b_shop_index:
  pattern:   /
  defaults:  { _controller: catalog:index }

n3b_shop_test:
  pattern:   /test

n3b_shop_catalog:
  resource:  "catalog.yml"

n3b_shop_basket:
  resource:  "basket.yml"
  prefix:    /basket

n3b_shop_checkout:
  resource:  "checkout.yml"
  prefix:    /checkout

n3b_shop_customer:
  resource:  "customer.yml"
  prefix:    /customer

